name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest
            
            # Stop and remove old container
            docker stop movie-list-backend || true
            docker rm movie-list-backend || true
            
            # Run new container
            docker run -d \
              --name movie-list-backend \
              --restart unless-stopped \
              -p 5000:5000 \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              -e PORT=5000 \
              ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest
            
            # Clean up old images
            docker image prune -af
