name: Build and Push Backend to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/movie-list-backend:latest
      
      - name: Deployment notification
        run: |
          echo "✅ Docker image pushed successfully!"
          echo "📝 Next steps:"
          echo "1. SSH to your EC2 instance: ssh -i ~/.ssh/movie-list-ec2-key.pem ubuntu@${{ secrets.EC2_HOST }}"
          echo "2. Run the auto-deploy script: ./auto-deploy.sh"
          echo "3. Or set up a cron job to automatically pull and restart"
